import {esc,money,hours,today,addDays,monday,minutes,timeLabel,statusText,subjectClass,dateKey,statsFor,accountEntries} from './utils.js';
import {estimatedFee,attentionFor,plannedChanges,scheduleConflicts,reviewCategory} from './workflows.js';
import {buildStatement} from './statement.js';
const main=document.querySelector('#main'), dialog=document.querySelector('#dialog');
let state={students:[],courses:[],payments:[],reviews:[],periods:[],meta:{}}, loaded=false;
let route=location.hash.slice(1)||'schedule', anchor=today(), view='week', selectedStudent='', studentSearch='', studentStatus='active';
let filterStudent='',filterStatus='',statsMode='month',statsStart=today().slice(0,7)+'-01',statsEnd=today(),statsStudent='';
let studentAttention='',studentTab='overview',recordMode='recent',recordStart=addDays(today(),-30),recordEnd=today();
let reviewStudent='',reviewType='',reviewStatus='pending',reviewPage=0,agendaMode='today',showFilters=false;
let toastTimer;
const calendarPositions=new Map();
const studentBy=id=>state.students.find(s=>s.id===id);
const courseBy=id=>state.courses.find(c=>c.id===id);
const displayMinutes=c=>c.status==='completed'&&c.actual_minutes!=null?c.actual_minutes:c.duration_minutes;
const option=(value,label,selected)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const studentOptions=(selected,all=false)=>`${all?option('','所有学生',selected):''}${state.students.map(s=>option(s.id,s.name+(s.status!=='active'?`（${statusText(s.status)}）`:''),selected)).join('')}`;
const notice=(text,tone='')=>`<div class="notice ${tone}">${text}</div>`;
const empty=(text,action='')=>`<div class="empty"><p>${text}</p>${action}</div>`;
const button=(action,text,id='',cls='')=>`<button type="button" data-action="${action}" ${id?`data-id="${esc(id)}"`:''} class="${cls}">${text}</button>`;
const field=(label,control,cls='')=>`<label class="field ${cls}"><span>${label}</span>${control}</label>`;
const input=(name,type,value='',attrs='')=>`<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}>`;
const dateShort=d=>d?`${Number(d.slice(5,7))}月${Number(d.slice(8,10))}日`:'日期待核对';
const attentionLabels={debt:'已欠费',low:'不足下次课费',unverified:'余额待核对',normal:''};
const balanceHTML=s=>`<span class="${s.balance_cents<0?'negative':''}">${s.balance_cents<0?'欠费 '+money(-s.balance_cents):money(s.balance_cents)}</span>${!s.balance_verified?'<small class="unverified">已记录 · 待核对</small>':''}`;
const feeHTML=c=>c.status==='scheduled'?`预计 ${money(estimatedFee(c,studentBy(c.student_id)))}<small>尚未扣费</small>`:c.status==='cancelled'?'不扣费':money(c.fee_cents);
function toast(message,undo=null){const el=document.querySelector('#toast');el.replaceChildren(document.createTextNode(message));if(undo){const b=document.createElement('button');b.textContent='撤销本次记课';b.onclick=async()=>{b.disabled=true;try{await undo();toast('已撤销本次记课，余额已恢复');}catch(e){toast(e.message);}};el.append(b);}el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},undo?12000:4500);}
async function api(path,method='GET',body){let response;try{response=await fetch(`/api${path}`,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});}catch{throw new Error('无法连接本地服务，请确认课时簿仍在运行。');}let data;try{data=await response.json();}catch{throw new Error('本地服务返回了无法读取的内容，请稍后重试。');}if(!response.ok)throw new Error(data.error||'保存失败，请重试。');return data;}
async function refresh(){state=await api('/state');loaded=true;render();}
async function mutate(path,method,body,message='已保存'){const result=await api(path,method,body);await refresh();toast(message);return result;}
function openDialog(title,body,onSubmit,footer='保存',wide=false){
 if(dialog.open)dialog.close();dialog.classList.toggle('wide',wide);
 dialog.innerHTML=`<form><header class="dialog-head"><h2 id="dialog-title">${title}</h2><button type="button" data-close aria-label="关闭对话框" class="icon-button">×</button></header><div class="dialog-body">${body}<p class="form-error" role="alert" hidden></p></div><footer class="dialog-foot"><button type="button" data-close>${onSubmit?'取消':'关闭'}</button>${onSubmit?`<button type="submit" class="primary">${footer}</button>`:''}</footer></form>`;
 dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.showModal();
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=e.submitter,error=dialog.querySelector('.form-error');error.hidden=true;if(submit)submit.disabled=true;try{const result=await onSubmit(Object.fromEntries(new FormData(e.target)));if(result!==false)dialog.close();}catch(err){error.textContent=err.message;error.hidden=false;}finally{if(submit)submit.disabled=false;}};
}
function confirmAction(title,content,action,label='确认'){openDialog(title,content,action,label);}
function header(_eyebrow,title,subtitle,actions=''){return `<header class="page-head"><div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${button('global-payment','＋ 记缴费')}${actions}</div></header>`;}
function render(){
 const calendar=main.querySelector('.calendar-scroll');if(calendar)calendarPositions.set(calendar.dataset.key,calendar.scrollTop);
 document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===route);if(a.dataset.nav===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const count=document.querySelector('#review-count');count.textContent=state.reviews.filter(r=>r.status==='pending').length||'';
 if(!loaded)return;if(route==='students')renderStudents();else if(route==='stats')renderStats();else if(route==='settings')renderSettings();else if(route==='reviews')renderReviews();else renderSchedule();
}
function filteredCourses(){return state.courses.filter(c=>(!filterStudent||c.student_id===filterStudent)&&(!filterStatus||c.status===filterStatus));}
function agenda(){
 const now=new Date(), nowMinutes=now.getHours()*60+now.getMinutes();
 const pending=state.courses.filter(c=>c.status==='scheduled'&&c.date&&(c.date<today()||(c.date===today()&&c.start_time&&minutes(c.start_time)+c.duration_minutes<=nowMinutes)));
 const daily=state.courses.filter(c=>c.date===today()&&c.status!=='cancelled');
 const list=(agendaMode==='pending'?pending:daily).filter(c=>!filterStudent||c.student_id===filterStudent).sort((a,b)=>a.date.localeCompare(b.date)||(a.start_time||'').localeCompare(b.start_time||''));
 return `<section class="agenda" aria-label="今日工作台"><div class="agenda-heading"><div class="actions"><button data-action="agenda-today" class="text-button ${agendaMode==='today'?'current':''}">今日 ${daily.length} 节</button><button data-action="agenda-pending" class="text-button ${agendaMode==='pending'?'current':''}">待记课 ${pending.length}</button></div><small>${agendaMode==='pending'?'已过计划结束时间，请确认实际是否上课':dateShort(today())+' · 课后确认，按实际时长扣费'}</small></div><div class="agenda-list">${list.length?list.map(c=>`<article class="agenda-item ${c.status}"><div class="agenda-time">${agendaMode==='pending'?`<small>${dateShort(c.date)}</small>`:''}${c.start_time||'时间待核对'}</div><div class="agenda-person"><strong>${esc(studentBy(c.student_id)?.name)}</strong><span>${esc(c.subject)} · ${hours(displayMinutes(c))}</span></div><div class="agenda-fee">${feeHTML(c)}</div><div class="actions">${c.status==='scheduled'?button('complete-course','记课',c.id,'primary'): '<span class="done-label">✓ 已记课</span>'}${button('course','详情',c.id,'text-button')}</div></article>`).join(''):`<p class="agenda-empty">${agendaMode==='pending'?'没有待确认的课程。':'今天暂未排课，可点击下方空档安排。'}</p>`}</div></section>`;
}
function renderSchedule(){
 const start=monday(anchor),end=addDays(start,6),courses=filteredCourses();
 main.innerHTML=header('',view==='week'?'每周课表':'每月课表',view==='week'?`${dateShort(start)} — ${dateShort(end)}`:`${anchor.slice(0,4)} 年 ${Number(anchor.slice(5,7))} 月`,button('new-course','安排课程','','primary'))+
 agenda()+`<section class="planner"><div class="planner-toolbar"><div class="actions"><div class="segmented"><button data-action="view-week" aria-pressed="${view==='week'}">周</button><button data-action="view-month" aria-pressed="${view==='month'}">月</button></div><button data-action="prev" class="icon-button" aria-label="上一${view==='week'?'周':'月'}">‹</button><button data-action="today">今天</button><button data-action="next" class="icon-button" aria-label="下一${view==='week'?'周':'月'}">›</button><label class="sr-only" for="anchor">课表日期</label><input type="date" id="anchor" value="${anchor}"></div><div class="actions"><span class="legend-inline"><i class="done-swatch"></i> 已上课</span><button data-action="toggle-filters" aria-expanded="${showFilters}">筛选${filterStudent||filterStatus?' · 已启用':''}</button>${button('copy-week','复制上周')}</div></div><div class="planner-filters" ${showFilters?'':'hidden'}><label>学生 <select id="filter-student">${studentOptions(filterStudent,true)}</select></label><label>状态 <select id="filter-status">${option('','所有状态',filterStatus)}${['scheduled','completed','cancelled'].map(s=>option(s,statusText(s),filterStatus)).join('')}</select></label><span class="muted">点击空档排课 · 拖动待上课程调课</span></div>${view==='week'?weekGrid(start,courses):monthGrid(courses)}</section>`;
 bindSchedule();
 const scroll=main.querySelector('.calendar-scroll');if(scroll){
  const key=monday(anchor);scroll.dataset.key=key;scroll.style.maxHeight=Math.max(320,innerHeight-(scroll.getBoundingClientRect().top+scrollY)-24)+'px';
  const week=courses.filter(c=>c.date>=start&&c.date<=end&&c.start_time&&c.status!=='cancelled');
  const focus=week.filter(c=>c.date===today());const times=(focus.length?focus:week).map(c=>minutes(c.start_time));
  const earliest=Math.min(8,...courses.filter(c=>c.date>=start&&c.date<=end&&c.start_time).map(c=>Math.floor(minutes(c.start_time)/60)));
  scroll.scrollTop=calendarPositions.get(key)??Math.max(0,((times.length?Math.min(...times):9*60)-earliest*60-30)/60*64);
 }
}
function courseChip(c,style=''){const s=studentBy(c.student_id);return `<button class="course ${subjectClass(c.subject)} ${c.status} ${c.conflict?'conflict':''}" data-action="${c.status==='scheduled'?'complete-course':'course'}" data-id="${esc(c.id)}" ${style?`style="${style}"`:''} draggable="${c.status==='scheduled'}" title="${esc(`${s?.name} · ${c.subject} · ${c.start_time||'时间待核对'} · ${statusText(c.status)}`)}"><span class="course-top"><strong>${esc(s?.name||'未知学生')}</strong><span class="subject-dot"></span></span><span>${esc(c.subject)} <span class="course-time">${c.start_time||'时间待核对'}${c.start_time?`–${timeLabel(minutes(c.start_time)+displayMinutes(c))}`:''}</span></span><small>${c.status==='completed'?`✓ 已上课 · ${hours(c.actual_minutes)}`:c.status==='cancelled'?'请假 / 取消':hours(c.duration_minutes)}${c.needs_review?' · 待核对':''}${c.conflict?' · 时间冲突':''}</small></button>`;}
function bindSchedule(){
 document.querySelector('#anchor').onchange=e=>{anchor=e.target.value||today();render();};
 document.querySelector('#filter-student').onchange=e=>{filterStudent=e.target.value;render();};document.querySelector('#filter-status').onchange=e=>{filterStatus=e.target.value;render();};
 main.querySelectorAll('.course[draggable="true"]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.id);e.dataTransfer.effectAllowed='move';});
 main.querySelectorAll('[data-date]').forEach(el=>{el.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';};el.ondrop=e=>{e.preventDefault();e.stopPropagation();const c=courseBy(e.dataTransfer.getData('text/plain'));if(c?.status==='scheduled')courseForm(c,{date:el.dataset.date,start_time:el.dataset.time||c.start_time});};});
}
function studentPicker(selected){return field('搜索学生',input('student_query','search','','placeholder="姓名或年级" autocomplete="off"'))+field('学生',`<select name="student_id" required>${studentOptions(selected)}</select>`);}
function bindStudentPicker(onChange=()=>{}){
 const query=dialog.querySelector('[name="student_query"]'),select=dialog.querySelector('[name="student_id"]');if(!query)return;
 query.oninput=()=>{const current=select.value;select.innerHTML=state.students.filter(s=>(s.name+' '+s.grade).includes(query.value.trim())).map(s=>option(s.id,s.name,current)).join('');onChange(select.value);};select.onchange=()=>onChange(select.value);
}
function courseForm(c=null,defaults={}){
 if(!state.students.length){studentForm();return;}
 const item={student_id:filterStudent||selectedStudent||state.students.find(s=>s.status==='active')?.id||state.students[0].id,date:anchor,start_time:'18:00',duration_minutes:120,notes:'',...c,...defaults};
 const subjects=[...new Set([...Object.keys(studentBy(item.student_id)?.rates||{}),...(c?.source?['数学','物理',c.subject]:[])])];item.subject=item.subject||subjects[0];
 const historical=!!c?.source;
 openDialog(c?'编辑课程':'安排课程',`<div class="form-grid">${c?field('学生',`<strong>${esc(studentBy(c.student_id)?.name)}</strong>`):studentPicker(item.student_id)}${field('科目',`<select name="subject" ${c&&!historical?'disabled':''}>${subjects.map(s=>option(s,s,item.subject)).join('')}</select>`)}${field(historical?'日期（未知可留空）':'日期',input('date','date',item.date,historical?'':'required'))}${field(historical?'开始时间（未知可留空）':'开始时间',input('start_time','time',item.start_time,`${historical?'':'required'} step="60"`))}${field('计划时长（小时）',input('duration_hours','number',item.duration_minutes/60,`required min="${historical?'0.01':'1'}" max="24" step="${historical?'any':'1'}"`))}${!c?field('每周重复至（可不填）',input('repeat_until','date','','min="'+item.date+'"')):''}${c?.series_id&&c.status==='scheduled'?field('修改范围',`<select name="scope">${option('one','仅本次','one')}${option('following','本次及以后待上课程','one')}</select>`):''}${field('备注',`<textarea name="notes" rows="2">${esc(item.notes)}</textarea>`,'full')}${c?.needs_review?field('核对已填写的信息','<span class="check"><input type="checkbox" name="reviewed">确认本次补充；仍缺失的事项继续保留</span>','full'):''}</div><div id="schedule-preview" aria-live="polite"></div>${historical?`<details><summary>原始来源</summary><p class="source">${esc(c.source)}</p></details>`:''}`,async f=>{
  const changes=plannedChanges(state.courses,c,f),conflicts=scheduleConflicts(state.courses,changes);
  if(conflicts.length&&!f.overlap_ack)throw new Error('此安排存在时间重叠，请查看下方冲突并确认继续。');
  const payload={date:f.date||null,start_time:f.start_time||null,duration_minutes:Math.round(Number(f.duration_hours)*60),notes:f.notes};
  if(c){payload.scope=f.scope||'one';if(historical)payload.subject=f.subject;if(f.reviewed)payload.needs_review=false;await mutate(`/courses/${c.id}`,'PATCH',payload);}
  else{payload.student_id=f.student_id;payload.subject=f.subject;if(f.repeat_until)payload.repeat_until=f.repeat_until;await mutate('/courses','POST',payload,'课程已安排');}
 });
 const preview=()=>{const f=Object.fromEntries(new FormData(dialog.querySelector('form'))),changes=plannedChanges(state.courses,c,f),conflicts=scheduleConflicts(state.courses,changes);dialog.querySelector('#schedule-preview').innerHTML=`${changes.length>1?notice(`将${c?'修改':'安排'} ${changes.length} 节课：${changes.slice(0,4).map(x=>dateShort(x.date)).join('、')}${changes.length>4?'等':''}。已完成课程保持原记录。`):''}${conflicts.length?notice(`<strong>有 ${conflicts.length} 处时间重叠</strong><ul>${conflicts.slice(0,5).map(({change,other})=>`<li>${dateShort(change.date)} ${change.start_time} 与 ${esc(studentBy(other.student_id)?.name)} ${other.start_time}–${timeLabel(minutes(other.start_time)+displayMinutes(other))} 重叠</li>`).join('')}</ul><label class="check"><input type="checkbox" name="overlap_ack">已知晓重叠，仍按此安排</label>`,'warning'):''}`;};
 dialog.querySelectorAll('[name="date"],[name="start_time"],[name="duration_hours"],[name="repeat_until"],[name="scope"]').forEach(x=>x.addEventListener('input',preview));
 if(!c)bindStudentPicker(id=>{const select=dialog.querySelector('[name="subject"]');select.innerHTML=Object.keys(studentBy(id)?.rates||{}).map(s=>option(s,s,select.value)).join('');preview();});preview();
}
function courseDetail(c){
 const s=studentBy(c.student_id);
 openDialog(`${esc(s?.name||'未知学生')} · ${esc(c.subject)}`,`<p class="detail-lead">${dateShort(c.date)} ${c.start_time||'时间待核对'}</p><dl class="key-values"><div><dt>状态</dt><dd>${statusText(c.status)}</dd></div><div><dt>计划课时</dt><dd>${hours(c.duration_minutes)}</dd></div><div><dt>实际课时</dt><dd>${c.status==='completed'?hours(c.actual_minutes):'—'}</dd></div><div><dt>${c.status==='scheduled'?'预计课费':'本次课费'}</dt><dd>${feeHTML(c)}</dd></div><div><dt>${s.balance_verified?'当前余额':'当前已记录余额'}</dt><dd>${balanceHTML(s)}</dd></div></dl>${c.conflict?notice('与其他课程时间重叠，请检查排期。','warning'):''}${c.needs_review?notice('历史信息尚未核对完整，待核对费用未计入确定账目。'):''}${c.notes?`<p class="preserve">${esc(c.notes)}</p>`:''}${c.source?`<details><summary>原始来源</summary><p class="source">${esc(c.source)}</p></details>`:''}<div class="dialog-actions">${c.status==='scheduled'?button('complete-course','记课并扣费',c.id,'primary'):c.status==='completed'?button('correct-course','更正课时 / 费用',c.id):button('reschedule-course','恢复为待上课',c.id)}${button('edit-course','调整时间 / 备注',c.id)}${button('payment','记缴费',s.id)}${button('open-student','学生账页',s.id)}</div><div class="dialog-actions">${c.status==='scheduled'?button('cancel-course','请假 / 取消',c.id)+(!c.source?button('delete-course','删除排课',c.id,'text-button danger'):''):c.status==='completed'?button('undo-course','撤销已上课',c.id,'text-button'):''}</div>`,null);
}
function completeForm(c,correct=false){
 const s=studentBy(c.student_id),rate=correct?c.hourly_rate_cents:s?.rates?.[c.subject];
 openDialog(correct?'更正已完成课程':'记课并扣费',`<p class="detail-lead">${esc(s?.name)} · ${esc(c.subject)} <small>${dateShort(c.date)} ${c.start_time||''}</small></p>${!correct?button('course','课程详情 / 调课',c.id,'text-button'):''}<div class="form-grid">${field('实际时长（小时）',input('actual_hours','number',(c.actual_minutes??c.duration_minutes)/60,`required min="${c.source?'0.01':'1'}" max="24" step="${c.source?'any':'1'}"`))}${field('本次小时价（元）',input('rate','number',rate==null?'':rate/100,`required min="0" step="0.01" ${correct?'':'readonly'}`))}${field('备注',`<textarea name="notes" rows="2">${esc(c.notes)}</textarea>`,'full')}</div>${c.source?`<details ${c.needs_review?'open':''}><summary>历史课程信息</summary><div class="form-grid">${field('日期（未知可留空）',input('date','date',c.date))}${field('开始时间（未知可留空）',input('start_time','time',c.start_time))}${field('科目',input('subject','text',c.subject,'required'))}</div><p class="source">${esc(c.source)}</p></details>`:''}<div id="completion-preview" class="completion-preview" aria-live="polite"></div>${!s?.balance_verified?notice('当前余额尚未核实，预览只反映已记录账目。'):''}${rate==null&&!correct?notice('该科目尚未设置单价，请先编辑学生档案。 '+button('edit-student','设置单价',s.id),'warning'):''}${c.needs_review?field('核对确认','<span class="check"><input type="checkbox" name="reviewed" required>已确认本次填写的时长和单价；未补齐的历史信息继续待核对</span>'):''}`,async f=>{
  const payload={status:'completed',actual_minutes:Math.round(Number(f.actual_hours)*60),notes:f.notes};if(correct)payload.hourly_rate_cents=Math.round(Number(f.rate)*100);
  if(c.source)Object.assign(payload,{date:f.date||null,start_time:f.start_time||null,subject:f.subject});if(c.needs_review&&f.reviewed)payload.needs_review=false;
  const result=await api(`/courses/${c.id}`,'PATCH',payload);await refresh();
  if(correct){toast(result.needs_review?'已保存，仍有历史信息待核对':'已更正，余额已重新计算');return;}
  const after=studentBy(s.id);toast(`${s.name} · 已记 ${hours(payload.actual_minutes)}，${after.balance_cents<0?'欠费 '+money(-after.balance_cents):'余额 '+money(after.balance_cents)}`,async()=>{await api(`/courses/${c.id}`,'PATCH',{status:'scheduled',actual_minutes:c.actual_minutes,hourly_rate_cents:c.hourly_rate_cents});await refresh();});
 },correct?'保存更正':'确认扣费');
 const preview=()=>{const h=Number(dialog.querySelector('[name="actual_hours"]').value),rateValue=dialog.querySelector('[name="rate"]').value,r=Number(rateValue),cost=rateValue===''?null:Math.round(h*r*100),balance=cost==null?null:s.balance_cents+(correct?(c.fee_cents||0):0)-cost;dialog.querySelector('#completion-preview').innerHTML=`<span>${h} 小时 × ${money(rateValue===''?null:Math.round(r*100))}</span><strong>${correct?'更正后课费':'本次扣费'} ${money(cost)}</strong><span>${correct?'更正后':'扣费后'}${s.balance_verified?'余额':'已记录余额'} <b class="${balance<0?'negative':''}">${balance<0?'欠费 '+money(-balance):money(balance)}</b></span>${correct&&c.fee_cents!=null&&cost!=null?`<span>原扣费 ${money(c.fee_cents)} · ${cost<c.fee_cents?'退回余额':'补扣'} ${money(Math.abs(cost-c.fee_cents))}</span>`:''}`;};
 dialog.querySelectorAll('input').forEach(i=>i.addEventListener('input',preview));preview();if(rate==null&&!correct)dialog.querySelector('[type="submit"]').disabled=true;
}
function rangeControls(){return `<div class="record-controls"><label>记录范围 <select id="record-mode">${option('recent','近 30 天',recordMode)}${option('all','全部记录',recordMode)}${state.periods.map(p=>option('period:'+p.id,p.name,recordMode)).join('')}${option('custom','自定义',recordMode)}</select></label>${recordMode!=='all'?`<label>从 <input id="record-start" type="date" value="${recordStart}"></label><label>至 <input id="record-end" type="date" value="${recordEnd}"></label>`:''}</div>`;}
const inRecordRange=e=>recordMode==='all'||(e.date&&e.date>=recordStart&&e.date<=recordEnd);
let recordLimit=30;
function courseTable(courses){return courses.length?`<div class="table-scroll"><table><thead><tr><th>日期 / 科目</th><th>课时</th><th>状态</th><th class="number">课费</th><th></th></tr></thead><tbody>${courses.map(c=>`<tr><td>${esc(c.date||'日期待核对')}<small>${c.start_time||'时间待核对'} · ${esc(c.subject)}</small></td><td>${hours(displayMinutes(c))}</td><td><span class="status ${c.status}">${statusText(c.status)}</span>${c.needs_review?'<small>待核对</small>':''}</td><td class="number">${feeHTML(c)}</td><td>${button('course','查看',c.id,'text-button')}</td></tr>`).join('')}</tbody></table></div>`:empty('所选范围没有课程。');}
function accountTable(entries,undated=[],verified=true){
 const all=[...entries,...(undated.length?[{divider:true},...undated]:[])];
 return `<div class="table-scroll"><table><thead><tr><th>日期 / 事项</th><th class="number">收入 / 支出</th><th class="number">本笔后${verified?'':'已记录'}余额</th><th></th></tr></thead><tbody>${all.map(e=>e.divider?'<tr><th colspan="4">日期待补 · 未纳入时间范围</th></tr>':`<tr><td>${esc(e.date||'日期待补')}<small>${e.type==='course'?`${esc(e.record.subject)} · ${hours(e.record.actual_minutes)} × ${money(e.record.hourly_rate_cents)}/小时`:({payment:'缴费',refund:'退款',adjustment:'余额调整'}[e.type])}</small>${e.notes?`<small>${esc(e.notes)}</small>`:''}</td><td class="number ${e.amount<0?'negative':''}">${e.amount==null?'待核对':`${e.amount>0?'+':''}${money(e.amount)}`}</td><td class="number ${e.balance<0?'negative':''}">${money(e.balance)}</td><td>${button(e.type==='course'?'course':'edit-payment',e.type==='course'?'查看':'更正',e.id,'text-button')}</td></tr>`).join('')}</tbody></table></div>`;
}
function studentDetail(s){
 const ledger=accountEntries(state,s.id),courses=state.courses.filter(c=>c.student_id===s.id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
 const pending=state.reviews.filter(r=>r.student_id===s.id&&r.status==='pending');const attention=attentionFor(s,state.courses);
 let content='';
 if(studentTab==='overview'){
  const upcoming=courses.filter(c=>c.status==='scheduled'&&c.date>=today()).reverse().slice(0,3);
  content=`${attention==='debt'||attention==='low'?notice(`${attention==='debt'?'当前有未补缴课费。':'当前余额不足下一次课费。'} ${button('payment','记缴费',s.id)}`,'warning'):''}${pending.length||!s.balance_verified?notice(`${pending.length} 项历史信息待核对。 ${button('student-reviews','查看核对事项',s.id)}`):''}<div class="section-line"><h3>接下来 ${upcoming.length} 节课</h3>${button('student-course','安排课程',s.id)}</div>${courseTable(upcoming)}<div class="section-line"><h3>最近流水</h3>${button('student-tab','全部流水','ledger','text-button')}</div>${ledger.dated.length?accountTable(ledger.dated.slice(-5).reverse(),[],s.balance_verified):empty('暂无有日期的账户流水。')}${ledger.undated.length?notice(`另有 ${ledger.undated.length} 条流水日期未知。 ${button('student-tab','查看待补日期流水','ledger','text-button')}`):''}`;
 }else{
  const dated=ledger.dated.filter(inRecordRange).reverse(),filtered=courses.filter(c=>!c.date||inRecordRange(c));
  content=rangeControls()+(recordStart>recordEnd&&recordMode!=='all'?notice('开始日期不能晚于结束日期。','warning'):'')+(studentTab==='ledger'?`<p class="muted small">最近记录在前；逐笔余额按从早到晚计算，同日无时刻的缴费先计入。</p>${ledger.uncertain?notice('存在日期或费用未知的记录，逐笔余额暂不显示。顶部余额仅反映已记录账目。'):''}${dated.length||ledger.undated.length?accountTable(dated.slice(0,recordLimit),ledger.undated,s.balance_verified):empty('所选范围没有流水。')}${dated.length>recordLimit?button('more-records',`再显示 30 条（共 ${dated.length} 条）`):''}`:courseTable(filtered.slice(0,recordLimit))+(filtered.length>recordLimit?button('more-records',`再显示 30 条（共 ${filtered.length} 条）`):''));
 }
 return `<header class="student-detail-head"><div><p class="muted small">${esc(s.grade||'未填年级')} · ${statusText(s.status)}</p><h2>${esc(s.name)}</h2><p class="muted">${Object.entries(s.rates||{}).map(([k,v])=>`${esc(k)} ${money(v)}/小时`).join(' · ')||'尚未设置科目'}</p></div>${button('edit-student','编辑档案',s.id)}</header><div class="balance-line"><div><span class="muted small">${s.balance_verified?'当前余额':'当前已记录余额'}</span><strong class="balance-value">${balanceHTML(s)}</strong></div><div class="actions">${button('payment','记缴费',s.id,'primary')}${button('statement','家长对账',s.id)}${button('reconcile','核对余额',s.id,'text-button')}</div></div><div class="detail-tabs" aria-label="学生记录分类">${[['overview','概览'],['ledger','账户流水'],['courses','课程记录']].map(([id,label])=>`<button data-action="student-tab" data-id="${id}" aria-pressed="${studentTab===id}">${label}</button>`).join('')}</div>${s.notes?`<p class="preserve muted small">${esc(s.notes)}</p>`:''}${content}`;
}
function renderStudents(){
 const students=state.students.filter(s=>(!studentStatus||s.status===studentStatus)&&(!studentSearch||(s.name+' '+s.grade).includes(studentSearch))&&(!studentAttention||attentionFor(s,state.courses)===studentAttention));
 if(!students.some(s=>s.id===selectedStudent))selectedStudent=students[0]?.id||'';
 main.innerHTML=header('','学生账页',`${students.length} 位学生 · 查看余额、课程与往来`,button('new-student','添加学生','','primary'))+`<div class="attention-filters"><button data-action="attention" data-id="" aria-pressed="${!studentAttention}">全部</button>${['debt','low','unverified'].map(k=>`<button data-action="attention" data-id="${k}" aria-pressed="${studentAttention===k}">${attentionLabels[k]} <b>${state.students.filter(s=>(!studentStatus||s.status===studentStatus)&&(!studentSearch||(s.name+' '+s.grade).includes(studentSearch))&&attentionFor(s,state.courses)===k).length}</b></button>`).join('')}</div><div class="students-layout"><section class="student-index"><div class="student-controls"><label class="sr-only" for="student-search">搜索姓名或年级</label><input id="student-search" type="search" placeholder="搜索姓名或年级" value="${esc(studentSearch)}"><label class="sr-only" for="student-status">学生状态</label><select id="student-status">${option('','全部状态',studentStatus)}${['active','paused','archived'].map(s=>option(s,statusText(s),studentStatus)).join('')}</select></div><div class="student-list">${students.map(s=>`<button class="student-row ${s.id===selectedStudent?'selected':''}" data-action="select-student" data-id="${esc(s.id)}"><span><strong>${esc(s.name)}</strong><small>${esc(s.grade||'未填年级')} · ${statusText(s.status)}</small></span><span class="student-balance">${balanceHTML(s)}${attentionFor(s,state.courses)==='low'?'<small class="negative">不足下次课费</small>':''}</span></button>`).join('')||empty('没有符合条件的学生。')}</div></section><section class="student-detail">${selectedStudent?studentDetail(studentBy(selectedStudent)):empty('添加学生后即可安排课程、记缴费。')}</section></div>`;
 document.querySelector('#student-search').oninput=e=>{studentSearch=e.target.value;const pos=e.target.selectionStart;renderStudents();const el=document.querySelector('#student-search');el.focus();el.setSelectionRange(pos,pos);};
 document.querySelector('#student-status').onchange=e=>{studentStatus=e.target.value;render();};
 const mode=document.querySelector('#record-mode');if(mode)mode.onchange=e=>{recordMode=e.target.value;recordLimit=30;if(recordMode==='recent'){recordStart=addDays(today(),-30);recordEnd=today();}else if(recordMode.startsWith('period:')){const p=state.periods.find(p=>p.id===recordMode.slice(7));recordStart=p.start;recordEnd=p.end;}render();};
 for(const key of ['start','end']){const el=document.querySelector('#record-'+key);if(el)el.onchange=e=>{if(key==='start')recordStart=e.target.value||today();else recordEnd=e.target.value||today();recordMode='custom';recordLimit=30;render();};}
}
function studentForm(s=null){
 const subjects=[...new Set(['数学','物理',...Object.keys(s?.rates||{})])],chosen=s?Object.keys(s.rates||{}):['数学'];
 openDialog(s?'编辑学生档案':'添加学生',`<div class="form-grid">${field('姓名',input('name','text',s?.name||'','required maxlength="80"'))}${field('年级',input('grade','text',s?.grade||'','maxlength="80"'))}${field('状态',`<select name="status">${['active','paused','archived'].map(v=>option(v,statusText(v),s?.status||'active')).join('')}</select>`)}</div><fieldset class="subject-fields"><legend>学习科目与小时价</legend><p class="muted small">勾选实际学习的科目，再填写价格。</p>${subjects.map((subject,i)=>`<div class="subject-rate"><label class="check"><input name="subject_${i}" type="checkbox" value="${esc(subject)}" ${chosen.includes(subject)?'checked':''}>${esc(subject)}</label>${field(`${esc(subject)}小时价（元）`,input('rate_'+i,'number',s?.rates?.[subject]==null?'':s.rates[subject]/100,`min="0" step="0.01" ${chosen.includes(subject)?'required':'disabled'}`))}</div>`).join('')}</fieldset>${field('备注',`<textarea name="notes" rows="2">${esc(s?.notes||'')}</textarea>`)}<p class="muted small">调价用于今后确认的课程，已完成课费保留当时价格。</p>`,async f=>{
  const rates={};subjects.forEach((subject,i)=>{if(f['subject_'+i])rates[subject]=Math.round(Number(f['rate_'+i])*100);});if(!Object.keys(rates).length)throw new Error('请至少选择一个学习科目。');
  const result=await api(s?`/students/${s.id}`:'/students',s?'PATCH':'POST',{name:f.name.trim(),grade:f.grade,status:f.status,notes:f.notes,rates});selectedStudent=result.id;studentSearch='';studentAttention='';studentStatus='';await refresh();toast('学生档案已保存');
 });
 dialog.querySelectorAll('[name^="subject_"]').forEach(el=>el.onchange=()=>{const rate=dialog.querySelector('[name="rate_'+el.name.split('_')[1]+'"]');rate.disabled=!el.checked;rate.required=el.checked;});
}
function paymentForm(studentId=null,p=null){
 if(!state.students.length){studentForm();return;}
 const selected=studentId||state.students.find(s=>s.status==='active')?.id||state.students[0].id;
 const matching=p?.source?state.reviews.filter(r=>r.status==='pending'&&r.kind==='payment_date_missing'&&r.student_id===p.student_id&&r.source===p.source):[];
 const unique=p&&state.payments.filter(x=>x.student_id===p.student_id&&x.source===p.source).length===1;
 const allowUnknown=p&&(p.source||!p.date);
 openDialog(p?'更正缴费记录':'记缴费',`${studentId?`<p class="detail-lead">${esc(studentBy(studentId)?.name)}</p>`:''}<div class="form-grid">${studentId?'':studentPicker(selected)}${field('类型',`<select name="kind">${option('payment','缴费',p?.kind||'payment')}${option('refund','退款',p?.kind||'payment')}${p?.kind==='adjustment'?option('adjustment','余额调整',p.kind):''}</select>`)}${field('日期',input('date','date',p?(p.date||''):today(),p&&!p.date?'disabled':'required'))}${allowUnknown?field('历史日期','<span class="check"><input name="date_unknown" type="checkbox" '+(!p.date?'checked':'')+'>日期尚未核实</span>','full'):''}${field('金额（元）',input('amount','number',p?Math.abs(p.amount_cents)/100:'',`required min="${p?.kind==='adjustment'?'0':'0.01'}" step="0.01"`))}${field('备注',`<textarea name="notes" rows="2">${esc(p?.notes||'')}</textarea>`,'full')}</div><div id="payment-preview" class="completion-preview" aria-live="polite"></div>${p&&!p.date?notice('这是一笔日期未知的历史款项。只改金额或备注会保留未知日期，不计入某月收款。'):''}${matching.length&&unique?notice(`补齐日期后，将同时完成对应的 ${matching.length} 条缴费日期核对。`):''}${p?.kind==='adjustment'?notice('余额调整保持原有正负方向，不计入实际收款。'):''}${p?.source?`<details><summary>原始来源</summary><p class="source">${esc(p.source)}</p></details>`:''}${p?`<div class="dialog-actions">${button('delete-payment','删除此笔记录',p.id,'text-button danger')}</div>`:''}`,async f=>{
  const sid=studentId||f.student_id,sign=p?.kind==='adjustment'&&p.amount_cents<0?-1:1;
  const payload={student_id:sid,date:f.date_unknown?null:f.date,kind:f.kind,amount_cents:Math.round(Number(f.amount)*100)*sign,notes:f.notes};
  if(payload.date&&matching.length&&unique)payload.review_ids=matching.map(r=>r.id);
  await mutate(p?`/payments/${p.id}`:'/payments',p?'PATCH':'POST',payload,'款项已保存，余额已更新');
 });
 const preview=()=>{const f=Object.fromEntries(new FormData(dialog.querySelector('form'))),s=studentBy(studentId||f.student_id),amount=Number(f.amount||0)*100,delta=f.kind==='refund'?-amount:(p?.kind==='adjustment'&&p.amount_cents<0?-amount:amount),balance=(s?.balance_cents||0)-(p?.amount_cents||0)+Math.round(delta);dialog.querySelector('#payment-preview').innerHTML=`<span>${esc(s?.name||'请选择学生')} · 当前${s?.balance_verified?'余额':'已记录余额'} ${money(s?.balance_cents)}</span><strong>保存后${s?.balance_verified?'':'已记录'}${balance<0?'欠费 '+money(-balance):'余额 '+money(balance)}</strong>`;};
 bindStudentPicker(preview);dialog.querySelectorAll('[name="amount"],[name="kind"]').forEach(el=>el.oninput=preview);
 const unknown=dialog.querySelector('[name="date_unknown"]');if(unknown)unknown.onchange=()=>{const date=dialog.querySelector('[name="date"]');date.disabled=unknown.checked;date.required=!unknown.checked;if(unknown.checked)date.value='';};preview();
}
function reconcileForm(s){
 const blocked=state.courses.filter(c=>c.student_id===s.id&&c.status==='completed'&&c.fee_cents==null);
 if(blocked.length){openDialog('先核对影响余额的课程',`<p>${esc(s.name)} 有 <strong>${blocked.length} 节已上课</strong> 的费用尚未确定，补齐后才能确认余额。</p>${notice('当前已记录余额不能代表实际余额。请补充已知信息；未知日期、时长和价格继续保留，不需要猜填。')}<div class="blocking-list">${blocked.slice(0,12).map(c=>`<div><span>${dateShort(c.date)} · ${esc(c.subject)}</span>${button('correct-course','核对这节课',c.id)}</div>`).join('')}</div>${button('student-reviews','查看全部核对事项',s.id)}`,null);return;}
 openDialog('核对学生余额',`<p class="detail-lead">${esc(s.name)}</p>${notice('按家长确认或完整账本填写当前余额。系统记录差额调整，保留历史课程和缴费。')}<p>当前已记录余额：${money(s.balance_cents)}</p><div class="form-grid">${field('核对后的余额（元）',input('balance','number',s.balance_cents/100,'required step="0.01"'))}${field('核对依据',`<textarea name="note" required rows="3" placeholder="与家长核对至哪一天，依据是什么">${''}</textarea>`,'full')}</div>`,async f=>mutate(`/students/${s.id}/reconcile`,'POST',{balance_cents:Math.round(Number(f.balance)*100),note:f.note},'余额已核对'),'确认余额');
}
function renderReviews(){
 const pending=state.reviews.filter(r=>r.status==='pending');
 const filtered=state.reviews.filter(r=>r.status===reviewStatus&&(!reviewStudent||r.student_id===reviewStudent)&&(!reviewType||reviewCategory(r)===reviewType)).sort((a,b)=>(studentBy(a.student_id)?.name||'').localeCompare(studentBy(b.student_id)?.name||'','zh-CN'));
 const pages=Math.max(1,Math.ceil(filtered.length/15));reviewPage=Math.min(reviewPage,pages-1);
 const page=filtered.slice(reviewPage*15,reviewPage*15+15),groups=new Map();for(const r of page){const key=r.student_id||'';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}
 main.innerHTML=header('','历史核对',`${pending.length} 项待处理 · 逐项补充信息，保留原始依据`)+`<div class="review-toolbar"><label>学生 <select id="review-student">${studentOptions(reviewStudent,true)}</select></label><label>问题类型 <select id="review-type">${option('','全部问题',reviewType)}${['日期','课时','费用','款项','其他'].map(t=>option(t,t,reviewType)).join('')}</select></label><label>处理状态 <select id="review-status">${option('pending','待核对',reviewStatus)}${option('resolved','已处理',reviewStatus)}</select></label></div><p class="muted small">补齐课程信息后自动核对对应缺失项；来源冲突等事项需记录依据后处理。</p>${page.length?[...groups].map(([sid,rows])=>`<section class="review-group"><div class="section-line"><h2>${esc(studentBy(sid)?.name||'其他历史记录')}</h2>${sid?button('open-student','学生账页',sid,'text-button'):''}</div>${rows.map(reviewRow).join('')}</section>`).join(''):empty('没有符合条件的核对事项。')}<div class="pagination">${button('review-prev','上一页','','') }<span>第 ${reviewPage+1} / ${pages} 页 · ${filtered.length} 项</span>${button('review-next','下一页')}</div>`;
 main.querySelector('[data-action="review-prev"]').disabled=reviewPage===0;main.querySelector('[data-action="review-next"]').disabled=reviewPage>=pages-1;
 for(const key of ['student','type','status'])document.querySelector('#review-'+key).onchange=e=>{if(key==='student')reviewStudent=e.target.value;else if(key==='type')reviewType=e.target.value;else reviewStatus=e.target.value;reviewPage=0;render();};
}
function matchingPayment(r){if(r.kind!=='payment_date_missing'||!r.source)return null;const matches=state.payments.filter(p=>p.student_id===r.student_id&&p.source===r.source);return matches.length===1?matches[0]:null;}
function reviewRow(r){const c=courseBy(r.course_id),p=matchingPayment(r);return `<article class="review-row"><div class="review-head"><span class="review-kind">${reviewCategory(r)}</span><strong>${esc(r.message)}</strong></div><details><summary>原始记录与核对依据</summary><p class="source">${esc(r.source||'未提供来源')}</p>${r.resolution?`<p class="preserve">${esc(r.resolution)}</p>`:''}</details><div class="actions">${c?button(c.status==='completed'?'correct-course':'edit-course','补充课程信息',c.id):p?button('edit-payment','补充缴费日期',p.id):r.student_id?button('student-ledger','查看学生流水',r.student_id):''}${button('review',r.status==='pending'?'记录核对结果':'查看处理结果',r.id,'text-button')}</div></article>`;}
function reviewForm(r){openDialog('记录核对结果',`<p>${esc(r.message)}</p><details><summary>原始来源</summary><p class="source">${esc(r.source)}</p></details><div class="form-grid">${field('处理状态',`<select name="status">${option('pending','仍待核对',r.status)}${option('resolved','已核对处理',r.status)}</select>`)}${field('核对依据',`<textarea name="resolution" rows="3" required>${esc(r.resolution)}</textarea>`,'full')}</div><p class="muted small">请先补充对应记录，再标记处理。此处不修改课程或款项。</p>`,async f=>mutate(`/reviews/${r.id}`,'PATCH',f,'核对结果已保存'));}
function renderSettings(){main.innerHTML=header('','设置','学期范围与本地备份')+`<section class="settings-section"><div class="section-title"><h2>学期与假期</h2><p>保存常用范围，统计与账页可直接选择。</p></div><div class="settings-content">${state.periods.map(p=>`<div class="setting-row"><div><strong>${esc(p.name)}</strong><small>${p.start} — ${p.end}</small></div>${button('delete-period','删除',p.id,'text-button danger')}</div>`).join('')||'<p>暂无学期范围。</p>'}${button('new-period','添加学期')}</div></section><section class="settings-section"><div class="section-title"><h2>数据与备份</h2><p>记录保存在这台 Mac。</p></div><div class="settings-content"><dl class="key-values"><div><dt>最近备份</dt><dd>${esc(state.meta.last_backup_at||'尚未备份')}</dd></div><div><dt>数据目录</dt><dd class="path">${esc(state.meta.data_dir)}</dd></div></dl><div class="actions">${button('backup','下载备份','','primary')}${button('restore','从备份恢复')}</div><p class="muted small">恢复会替换全部数据；操作前自动保留一份当前数据库备份。</p></div></section><p class="version">课时簿 ${esc(state.meta.app_version)} · 本地使用</p>`;}
function statementForm(id){
 let doc=null;
 const initialStart=recordMode==='all'?today().slice(0,7)+'-01':recordStart,initialEnd=recordMode==='all'?today():recordEnd;
 openDialog('家长对账',`<p class="detail-lead">${esc(studentBy(id)?.name)}</p><div class="form-grid">${field('对账开始日期',input('start','date',initialStart,'required'))}${field('对账结束日期',input('end','date',initialEnd,'required'))}</div><p class="muted small">预览后可复制文字，或在系统打印窗口选择“存储为 PDF”。</p><div class="actions"><button type="button" id="copy-statement">复制对账文字</button><button type="button" id="print-statement">打印 / 保存 PDF</button></div><iframe id="statement-preview" title="家长对账预览" sandbox="allow-same-origin allow-modals"></iframe>`,null,'',true);
 const update=()=>{const start=dialog.querySelector('[name="start"]').value,end=dialog.querySelector('[name="end"]').value,error=dialog.querySelector('.form-error');try{doc=buildStatement(state,id,start,end);dialog.querySelector('#statement-preview').srcdoc=doc.html;error.hidden=true;}catch(e){doc=null;error.textContent=e.message;error.hidden=false;}dialog.querySelector('#copy-statement').disabled=!doc;dialog.querySelector('#print-statement').disabled=!doc;};
 dialog.querySelectorAll('input').forEach(el=>el.onchange=update);
 dialog.querySelector('#copy-statement').onclick=async()=>{try{await navigator.clipboard.writeText(doc.text);toast('对账文字已复制，可粘贴给家长');}catch{const error=dialog.querySelector('.form-error');error.textContent='复制未获浏览器允许，请在下方预览中选中文字复制。';error.hidden=false;}};
 dialog.querySelector('#print-statement').onclick=()=>{const frame=dialog.querySelector('#statement-preview');frame.contentWindow.focus();frame.contentWindow.print();};update();
}
function openStudent(id,tab='overview'){selectedStudent=id;studentSearch='';studentAttention='';studentStatus='';studentTab=tab;recordLimit=30;if(dialog.open)dialog.close();if(route==='students')render();else location.hash='students';}
async function handleAction(action,id,el){
 const c=courseBy(id);
 switch(action){
 case'all-reviews':reviewStudent='';reviewType='';reviewPage=0;location.hash='reviews';break;
 case'global-payment':paymentForm();break;
 case'new-course':courseForm();break;case'slot':courseForm(null,{date:el.dataset.date,start_time:el.dataset.time});break;
 case'course':courseDetail(c);break;case'edit-course':courseForm(c);break;case'complete-course':completeForm(c);break;case'correct-course':completeForm(c,true);break;
 case'cancel-course':confirmAction('请假 / 取消课程',`<p>${esc(studentBy(c.student_id)?.name)} · ${dateShort(c.date)} ${c.start_time||''}</p><p>仅取消本次课程，不扣课费。</p>`,()=>mutate(`/courses/${id}`,'PATCH',{status:'cancelled'},'本次课程已取消'),'确认取消本次');break;
 case'undo-course':confirmAction('撤销上课确认',`<p>恢复为待上课，退回已扣课费 ${money(c.fee_cents)}。</p>`,()=>mutate(`/courses/${id}`,'PATCH',{status:'scheduled'},'已撤销上课确认'),'撤销确认');break;
 case'reschedule-course':await mutate(`/courses/${id}`,'PATCH',{status:'scheduled'});dialog.close();break;
 case'delete-course':confirmAction('删除这次排课',`<p>删除 ${esc(studentBy(c.student_id)?.name)} ${dateShort(c.date)} 的待上课程。其他重复课程保持原样。</p>`,()=>mutate(`/courses/${id}`,'DELETE',undefined,'排课已删除'),'删除排课');break;
 case'copy-week':confirmAction('复制上周到当前周',`<p>将 ${dateShort(addDays(monday(anchor),-7))} 起的一周复制到 ${dateShort(monday(anchor))} 起的一周。取消的课程不复制，相同排课自动跳过。</p>`,async()=>{const r=await api('/courses/copy-week','POST',{week_start:monday(anchor)});await refresh();toast(`已复制 ${r.created.length} 节课，跳过 ${r.skipped} 节`);},'复制课程');break;
 case'view-week':view='week';render();break;case'view-month':view='month';render();break;
 case'prev':case'next':{const n=action==='prev'?-1:1;if(view==='week')anchor=addDays(anchor,7*n);else{const d=new Date(`${anchor.slice(0,7)}-01T12:00:00`);d.setMonth(d.getMonth()+n);anchor=dateKey(d);}render();break;}
 case'today':anchor=today();render();break;case'toggle-filters':showFilters=!showFilters;render();break;
 case'agenda-today':agendaMode='today';render();break;case'agenda-pending':agendaMode='pending';render();break;
 case'new-student':studentForm();break;case'edit-student':studentForm(studentBy(id));break;
 case'select-student':selectedStudent=id;studentTab='overview';recordLimit=30;render();window.scrollTo(0,0);break;
 case'open-student':openStudent(id);break;case'student-ledger':openStudent(id,'ledger');recordMode='all';render();break;
 case'student-tab':studentTab=id;recordLimit=30;render();break;case'more-records':recordLimit+=30;render();break;
 case'attention':studentAttention=id||'';render();break;
 case'student-course':courseForm(null,{student_id:id,date:today()});break;
 case'payment':paymentForm(id);break;case'edit-payment':{const p=state.payments.find(p=>p.id===id);paymentForm(p.student_id,p);break;}
 case'delete-payment':confirmAction('删除缴费记录','<p>此笔记录将从流水移除，学生余额随之重新计算。</p>',()=>mutate(`/payments/${id}`,'DELETE',undefined,'缴费记录已删除'),'删除记录');break;
 case'reconcile':reconcileForm(studentBy(id));break;
 case'student-reviews':reviewStudent=id;reviewType='';reviewStatus='pending';reviewPage=0;if(dialog.open)dialog.close();if(route==='reviews')render();else location.hash='reviews';break;
 case'review':reviewForm(state.reviews.find(r=>r.id===id));break;case'review-prev':reviewPage--;render();window.scrollTo(0,0);break;case'review-next':reviewPage++;render();window.scrollTo(0,0);break;
 case'statement':statementForm(id);break;
 case'new-period':periodForm();break;case'delete-period':confirmAction('删除学期范围','<p>删除范围不会影响课程和账目。</p>',()=>mutate(`/periods/${id}`,'DELETE'),'删除范围');break;
 case'backup':{const backup=await api('/backup'),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`课时簿备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await refresh();toast('已生成备份下载');break;}
 case'restore':restoreForm();break;case'retry':await refresh();break;
 }
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;try{await handleAction(el.dataset.action,el.dataset.id,el);}catch(err){if(dialog.open){const error=dialog.querySelector('.form-error');error.textContent=err.message;error.hidden=false;}else toast(err.message);}});
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'schedule';render();window.scrollTo(0,0);main.focus({preventScroll:true});});
setStatsRange('month');
refresh().catch(err=>{main.innerHTML=header('','课时簿暂时无法打开','本地记录仍保存在这台 Mac。')+empty(esc(err.message),button('retry','重新连接','','primary'));});

function weekGrid(start,courses){const days=Array.from({length:7},(_,i)=>addDays(start,i));const known=courses.filter(c=>days.includes(c.date)&&c.start_time);const earliest=Math.min(8,...known.map(c=>Math.floor(minutes(c.start_time)/60)));const latest=Math.max(22,...known.map(c=>Math.ceil((minutes(c.start_time)+(displayMinutes(c)||120))/60)));const height=(latest-earliest)*64;let html=`<div class="calendar-scroll"><div class="week-header"><div class="time-zone">时间</div>${days.map((d,i)=>`<div class="day-title ${d===today()?'is-today':''}"><small>周${'一二三四五六日'[i]}</small><strong>${Number(d.slice(8))}</strong></div>`).join('')}</div><div class="week-body" style="--calendar-height:${height}px"><div class="time-rail">${Array.from({length:latest-earliest+1},(_,i)=>`<span style="top:${i*64}px">${String(earliest+i).padStart(2,'0')}:00</span>`).join('')}</div>`;for(const d of days){const dayCourses=known.filter(c=>c.date===d).sort((a,b)=>minutes(a.start_time)-minutes(b.start_time));html+=`<div class="day-column ${d===today()?'today-column':''}" data-date="${d}">${Array.from({length:(latest-earliest)*2},(_,i)=>`<button class="time-slot" data-action="slot" data-date="${d}" data-time="${timeLabel(earliest*60+i*30)}" aria-label="${dateShort(d)} ${timeLabel(earliest*60+i*30)} 安排课程"></button>`).join('')}`;const layouts=[];for(const c of dayCourses){const startM=minutes(c.start_time),endM=startM+(displayMinutes(c)||120);const overlaps=layouts.filter(l=>l.end>startM);let col=0;while(overlaps.some(l=>l.col===col))col++;layouts.push({c,start:startM,end:endM,col});}for(const l of layouts){const connected=layouts.filter(o=>o.start<l.end&&o.end>l.start);const cols=Math.max(...connected.map(o=>o.col))+1;html+=courseChip(l.c,`top:${(l.start-earliest*60)/60*64}px;height:${Math.max(40,(l.end-l.start)/60*64-4)}px;left:calc(${l.col/cols*100}% + 3px);width:calc(${100/cols}% - 6px)`);}html+='</div>';}html+='</div></div>';const unknown=courses.filter(c=>days.includes(c.date)&&!c.start_time);if(unknown.length)html+=`<div class="undated"><h3>开始时间待核对</h3><div class="course-strip">${unknown.map(c=>courseChip(c)).join('')}</div></div>`;return html;}
function monthGrid(courses){const first=anchor.slice(0,7)+'-01',start=monday(first);return `<div class="month-scroll"><div class="month-labels">${[...'一二三四五六日'].map(d=>`<span>周${d}</span>`).join('')}</div><div class="month-grid">${Array.from({length:42},(_,i)=>{const d=addDays(start,i),list=courses.filter(c=>c.date===d).sort((a,b)=>(a.start_time||'').localeCompare(b.start_time||''));return `<div class="month-day ${d.slice(0,7)!==anchor.slice(0,7)?'outside':''}" data-date="${d}"><button class="month-date ${d===today()?'is-today':''}" data-action="slot" data-date="${d}" data-time="09:00" aria-label="${d} 安排课程">${Number(d.slice(8))}</button>${list.map(c=>courseChip(c)).join('')}</div>`;}).join('')}</div></div>`;}
function setStatsRange(mode){statsMode=mode;const now=today();if(mode==='week'){statsStart=monday(now);statsEnd=addDays(statsStart,6);}else if(mode==='month'){statsStart=now.slice(0,7)+'-01';const d=new Date(`${statsStart}T12:00:00`);d.setMonth(d.getMonth()+1);d.setDate(0);statsEnd=dateKey(d);}else if(mode.startsWith('period:')){const p=state.periods.find(p=>p.id===mode.slice(7));if(p){statsStart=p.start;statsEnd=p.end;}}}
function renderStats(){const result=statsFor(state,statsStart,statsEnd,statsStudent);const rows=state.students.filter(s=>!statsStudent||s.id===statsStudent).map(s=>({s,...statsFor(state,statsStart,statsEnd,s.id)})).filter(r=>r.courses.length||r.payments.length||r.undatedCourses||r.undatedPayments);main.innerHTML=header('TEACHING & ACCOUNTS','课时与收支统计','实际授课与实际收款分别统计，不把充值当作课费。')+`<div class="stats-toolbar"><label>统计区间 <select id="stats-mode">${option('week','本周',statsMode)}${option('month','本月',statsMode)}${state.periods.map(p=>option('period:'+p.id,p.name,statsMode)).join('')}${option('custom','自定义',statsMode)}</select></label><label>从 <input type="date" id="stats-start" value="${statsStart}"></label><label>至 <input type="date" id="stats-end" value="${statsEnd}"></label><label class="sr-only" for="stats-student">统计学生</label><select id="stats-student">${studentOptions(statsStudent,true)}</select></div>${statsStart>statsEnd?notice('开始日期不能晚于结束日期。','warning'):''}<div class="stat-band"><div><span>实际课时</span><strong>${Number((result.minutes/60).toFixed(2))}<small> 小时</small></strong><p>已完成且实际时长已知</p></div><div><span>已产生课费</span><strong>${money(result.fee)}</strong><p>确定的已完成课程费用</p></div><div><span>实际净收款</span><strong>${money(result.received)}</strong><p>缴费 − 退款，不含余额调整</p></div></div>${result.undatedCourses||result.undatedPayments?notice(`另有 ${result.undatedCourses} 节已上课、${result.undatedPayments} 笔款项日期未知，未纳入此时段。 ${button('all-reviews','查看历史核对')}`):''}${result.unknown?notice(`区间内有 ${result.unknown} 节已完成课程待核对；未知时长与未知费用未计入对应合计。`):''}${result.adjusted?notice(`区间内另有余额调整 ${money(result.adjusted)}，未计入实际净收款。`):''}<div class="section-line"><h3>按学生明细</h3><span class="muted">${statsStart} — ${statsEnd}</span></div>${rows.length?`<div class="table-scroll"><table><thead><tr><th>学生</th><th class="number">实际课时</th><th class="number">课费</th><th class="number">实际净收款</th><th class="number">余额调整</th><th>核对</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${button('open-student',esc(r.s.name),r.s.id,'text-button')}</td><td class="number">${hours(r.minutes)}</td><td class="number">${money(r.fee)}</td><td class="number">${money(r.received)}</td><td class="number">${money(r.adjusted)}</td><td>${r.unknown||r.undatedCourses||r.undatedPayments?`${r.unknown} 节待核对 · ${r.undatedCourses+r.undatedPayments} 条缺日期`:'—'}</td></tr>`).join('')}</tbody></table></div>`:empty('这个区间还没有已完成课程或缴费记录。')}`;document.querySelector('#stats-mode').onchange=e=>{setStatsRange(e.target.value);render();};for(const id of ['start','end'])document.querySelector('#stats-'+id).onchange=e=>{if(id==='start')statsStart=e.target.value||today();else statsEnd=e.target.value||today();statsMode='custom';render();};document.querySelector('#stats-student').onchange=e=>{statsStudent=e.target.value;render();};}
function periodForm(){openDialog('添加学期',`<div class="form-grid">${field('名称',input('name','text','','required placeholder="例如：秋季学期"'),'full')}${field('开始日期',input('start','date',today(),'required'))}${field('结束日期',input('end','date',today(),'required'))}</div>`,async f=>{if(f.start>f.end)throw new Error('结束日期不能早于开始日期。');await mutate('/periods','POST',f);});}
function restoreForm(){openDialog('从 JSON 备份恢复',`${notice('恢复将覆盖当前全部学生、课程、缴费、学期和核对记录。系统会自动保存恢复前备份。','warning')}${field('选择课时簿 JSON 备份','<input type="file" name="backup_file" accept="application/json,.json" required>')}${field('确认覆盖',input('confirmation','text','','required placeholder="请输入：覆盖恢复" autocomplete="off"'))}`,async f=>{if(f.confirmation!=='覆盖恢复')throw new Error('请输入“覆盖恢复”以确认覆盖当前数据。');const file=dialog.querySelector('[name="backup_file"]').files[0];if(!file)throw new Error('请选择备份文件。');let backup;try{backup=JSON.parse(await file.text());}catch{throw new Error('文件不是有效的 JSON 备份。');}await mutate('/restore','POST',{backup},'备份已恢复');selectedStudent='';render();},'覆盖并恢复');}
